## Setup

### Import packages

Let's begin by importing the required packages and modules. In case you want to replicate this in your local workstation, we used *Tensorflow v2.6* and *TFX v1.3.0*.

In [1]:
import tensorflow as tf

from tfx import v1 as tfx

from tfx.orchestration.experimental.interactive.interactive_context import InteractiveContext
from google.protobuf.json_format import MessageToDict

import os
import pprint
pp = pprint.PrettyPrinter()

c:\Users\Shrey Patel\Desktop\TFX_Labs_TFX_Lab1\.venv310\lib\site-packages\google\api_core\_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.20) which Google will stop supporting in new releases of google.api_core once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.api_core past that date.
  warnings.warn(message, FutureWarning)
c:\Users\Shrey Patel\Desktop\TFX_Labs_TFX_Lab1\.venv310\lib\site-packages\google\api_core\_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.20) which Google will stop supporting in new releases of google.cloud.bigquery_storage_v1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.bigquery_storage_v1 past that date.
  warnings.warn(message, FutureWarning)
c:\Users\Shrey Patel\Desktop\TFX_Labs_TFX_Lab1\.venv310\lib\site-packages\google\api_core\_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.20) which Google will stop supporting in new releases of google.pubsub_v1 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.pubsub_v1 past that date.
  warnings.warn(message, FutureWarning)
c:\Users\Shrey Patel\Desktop\TFX_Labs_TFX_Lab1\.venv310\lib\site-packages\google\api_core\_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.20) which Google will stop supporting in new releases of google.cloud.resourcemanager_v3 once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.cloud.resourcemanager_v3 past that date.
  warnings.warn(message, FutureWarning)

### Define paths

You will define a few global variables to indicate paths in the local workspace.

In [2]:
# location of the pipeline metadata store
_pipeline_root = 'C:\\tmp\\tfx'

# directory of the raw data files
_data_root = './data/bike_data'

# path to the raw training data
_data_filepath = os.path.join(_data_root, 'SeoulBikeData.csv')

In [ ]:
import pandas as pd
import os
import urllib.request

# Create directory
os.makedirs(_data_root, exist_ok=True)

# Download and format dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00560/SeoulBikeData.csv"
temp_file = os.path.join(_data_root, "raw_bike_data.csv")

if not os.path.exists(_data_filepath):
    print("Downloading dataset...")
    urllib.request.urlretrieve(url, temp_file)
    print("Formatting dataset...")
    # Read with ISO-8859-1 encoding
    df = pd.read_csv(temp_file, encoding='ISO-8859-1')
    
    import re
    df.columns = [re.sub(r'[^a-zA-Z0-9_]', '_', col) for col in df.columns]
    
    # Save as UTF-8
    df.to_csv(_data_filepath, index=False, encoding='utf-8')
    print("Dataset ready.")
else:
    print("Dataset already exists.")

Dataset already exists.

### Preview the  dataset

You will again be using the [Census Income dataset](https://archive.ics.uci.edu/ml/datasets/Adult) from the Week 1 ungraded lab so you can compare outputs when just using stand-alone TFDV and when using it under TFX. Just to remind, the data can be used to predict if an individual earns more than or less than 50k US Dollars annually. Here is the description of the features again: 


* **age**: continuous.
* **workclass**: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
* **fnlwgt**: continuous.
* **education**: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
* **education-num**: continuous.
* **marital-status**: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
* **occupation**: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
* **relationship**: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
* **race**: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
* **sex**: Female, Male.
* **capital-gain**: continuous.
* **capital-loss**: continuous.
* **hours-per-week**: continuous.
* **native-country**: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.

### Create the Interactive Context

When pushing to production, you want to automate the pipeline execution using orchestrators such as [Apache Beam](https://beam.apache.org/) and [Kubeflow](https://www.kubeflow.org/). You will not be doing that just yet and will instead execute the pipeline from this notebook. When experimenting in a notebook environment, you will be *manually* executing the pipeline components (i.e. you are the orchestrator). For that, TFX provides the [Interactive Context](https://github.com/tensorflow/tfx/blob/master/tfx/orchestration/experimental/interactive/interactive_context.py) so you can step through each component and inspect its outputs.

You will initialize the `InteractiveContext` below. This will create a database in the `_pipeline_root` directory which the different components will use to save or get the state of the component executions. You will learn more about this in Week 3 when we discuss ML Metadata. For now, you can think of it as the data store that makes it possible for the different pipeline components to work together. 

*Note: You can configure the database to connect to but for this exercise, we will just use the default which is a newly created local sqlite file.* ***You will see the warning after running the cell below and you can safely ignore it.***

In [5]:
# Initialize the InteractiveContext with a local sqlite file.
# If you leave `_pipeline_root` blank, then the db will be created in a temporary directory.
# You can safely ignore the warning about the missing config file.
context = InteractiveContext(pipeline_root=_pipeline_root)

WARNING:absl:InteractiveContext metadata_connection_config not provided: using SQLite ML Metadata database at C:\tmp\tfx\metadata.sqlite.

## Run TFX components interactively

With that, you can now run the pipeline interactively. You will see how to do that as you go through the different components below.

### ExampleGen

You will start the pipeline with the [ExampleGen](https://www.tensorflow.org/tfx/guide/examplegen) component. This  will:

*   split the data into training and evaluation sets (by default: 2/3 train, 1/3 eval).
*   convert each data row into `tf.train.Example` format. This [protocol buffer](https://developers.google.com/protocol-buffers) is designed for Tensorflow operations and is used by the TFX components.
*   compress and save the data collection under the `_pipeline_root` directory for other components to access. These examples are stored in `TFRecord` format. This optimizes read and write operations within Tensorflow especially if you have a large collection of data.

Its constructor takes the path to your data source/directory. In our case, this is the `_data_root` path. The component supports several data sources such as CSV, tf.Record, and BigQuery. Since our data is a CSV file, we will use [CsvExampleGen](https://www.tensorflow.org/tfx/api_docs/python/tfx/components/CsvExampleGen) to ingest the data.

Run the cell below to instantiate `CsvExampleGen`.

In [6]:
# Instantiate ExampleGen with the input CSV dataset
example_gen = tfx.components.CsvExampleGen(input_base=_data_root)

You can execute the component by calling the `run()` method of the `InteractiveContext`.

In [7]:
# Execute the component
context.run(example_gen)

WARNING:apache_beam.runners.interactive.interactive_environment:Dependencies required for Interactive Beam PCollection visualization are not available, please use: `pip install apache-beam[interactive]` to install necessary dependencies to enable all data visualization features.

WARNING:apache_beam.io.tfrecordio:Couldn't find python-snappy so the implementation of _TFRecordUtil._masked_crc32c is not as fast as it could be.

ExecutionResult(
    component_id: CsvExampleGen
    execution_id: 30
    outputs:
        examples: OutputChannel(artifact_type=Examples, producer_component_id=CsvExampleGen, output_key=examples, additional_properties={}, additional_custom_properties={}, _input_trigger=None)

You will notice that an output cell showing the execution results is automatically shown. This metadata is recorded into the database created earlier. This allows you to keep track of your project runs. For example, if you run it again, you will notice the `.execution_id` incrementing.

The output of the components are called *artifacts* and you can see an example by navigating through  `.component.outputs > ['examples'] > Channel > ._artifacts > [0]` above. It shows information such as where the converted data is stored (`.uri`) and the splits generated (`.split_names`).

You can also examine the output artifacts programmatically with the code below.

In [8]:
# get the artifact object
artifact = example_gen.outputs['examples'].get()[0]

# print split names and uri
print(f'split names: {artifact.split_names}')
print(f'artifact uri: {artifact.uri}')

split names: ["train", "eval"]
artifact uri: C:\tmp\tfx\CsvExampleGen\examples\30

In [10]:
# Get the list of files in this directory (all compressed TFRecord files)
tfrecord_filenames = [os.path.join(train_uri, name)
                      for name in os.listdir(train_uri)]

# Create a `TFRecordDataset` to read these files
dataset = tf.data.TFRecordDataset(tfrecord_filenames, compression_type="GZIP")

In [11]:
# Define a helper function to get individual examples
def get_records(dataset, num_records):
    '''Extracts records from the given dataset.
    Args:
        dataset (TFRecordDataset): dataset saved by ExampleGen
        num_records (int): number of records to preview
    '''
    
    # initialize an empty list
    records = []
    
    # Use the `take()` method to specify how many records to get
    for tfrecord in dataset.take(num_records):
        
        # Get the numpy property of the tensor
        serialized_example = tfrecord.numpy()
        
        # Initialize a `tf.train.Example()` to read the serialMessageToDictized data
        example = tf.train.Example()
        
        # Read the example data (output is a protocol buffer message)
        example.ParseFromString(serialized_example)
        
        # convert the protocol bufffer message to a Python dictionary
        example_dict = (MessageToDict(example))
        
        # append to the records list
        records.append(example_dict)
        
    return records

In [12]:
# Get 3 records from the dataset
sample_records = get_records(dataset, 3)

# Print the output
pp.pprint(sample_records)

[{'features': {'feature': {'Date': {'bytesList': {'value': ['MDEvMTIvMjAxNw==']}},
                           'Dew_point_temperature__C_': {'floatList': {'value': [-17.6]}},
                           'Functioning_Day': {'bytesList': {'value': ['WWVz']}},
                           'Holiday': {'bytesList': {'value': ['Tm8gSG9saWRheQ==']}},
                           'Hour': {'int64List': {'value': ['0']}},
                           'Humidity___': {'int64List': {'value': ['37']}},
                           'Rainfall_mm_': {'floatList': {'value': [0.0]}},
                           'Rented_Bike_Count': {'int64List': {'value': ['254']}},
                           'Seasons': {'bytesList': {'value': ['V2ludGVy']}},
                           'Snowfall__cm_': {'floatList': {'value': [0.0]}},
                           'Solar_Radiation__MJ_m2_': {'floatList': {'value': [0.0]}},
                           'Temperature__C_': {'floatList': {'value': [-5.2]}},
                           'Visibility__10m_': {'int64List': {'value': ['2000']}},
                           'Wind_speed__m_s_': {'floatList': {'value': [2.2]}}}}},
 {'features': {'feature': {'Date': {'bytesList': {'value': ['MDEvMTIvMjAxNw==']}},
                           'Dew_point_temperature__C_': {'floatList': {'value': [-17.6]}},
                           'Functioning_Day': {'bytesList': {'value': ['WWVz']}},
                           'Holiday': {'bytesList': {'value': ['Tm8gSG9saWRheQ==']}},
                           'Hour': {'int64List': {'value': ['1']}},
                           'Humidity___': {'int64List': {'value': ['38']}},
                           'Rainfall_mm_': {'floatList': {'value': [0.0]}},
                           'Rented_Bike_Count': {'int64List': {'value': ['204']}},
                           'Seasons': {'bytesList': {'value': ['V2ludGVy']}},
                           'Snowfall__cm_': {'floatList': {'value': [0.0]}},
                           'Solar_Radiation__MJ_m2_': {'floatList': {'value': [0.0]}},
                           'Temperature__C_': {'floatList': {'value': [-5.5]}},
                           'Visibility__10m_': {'int64List': {'value': ['2000']}},
                           'Wind_speed__m_s_': {'floatList': {'value': [0.8]}}}}},
 {'features': {'feature': {'Date': {'bytesList': {'value': ['MDEvMTIvMjAxNw==']}},
                           'Dew_point_temperature__C_': {'floatList': {'value': [-17.7]}},
                           'Functioning_Day': {'bytesList': {'value': ['WWVz']}},
                           'Holiday': {'bytesList': {'value': ['Tm8gSG9saWRheQ==']}},
                           'Hour': {'int64List': {'value': ['2']}},
                           'Humidity___': {'int64List': {'value': ['39']}},
                           'Rainfall_mm_': {'floatList': {'value': [0.0]}},
                           'Rented_Bike_Count': {'int64List': {'value': ['173']}},
                           'Seasons': {'bytesList': {'value': ['V2ludGVy']}},
                           'Snowfall__cm_': {'floatList': {'value': [0.0]}},
                           'Solar_Radiation__MJ_m2_': {'floatList': {'value': [0.0]}},
                           'Temperature__C_': {'floatList': {'value': [-6.0]}},
                           'Visibility__10m_': {'int64List': {'value': ['2000']}},
                           'Wind_speed__m_s_': {'floatList': {'value': [1.0]}}}}}]

Now that `ExampleGen` has finished ingesting the data, the next step is data analysis.

### StatisticsGen
The [StatisticsGen](https://www.tensorflow.org/tfx/guide/statsgen) component computes statistics over your dataset for data analysis, as well as for use in downstream components (i.e. next steps in the pipeline). As mentioned earlier, this component uses TFDV under the hood so its output will be familiar to you.

`StatisticsGen` takes as input the dataset we just ingested using `CsvExampleGen`.

In [13]:
# Instantiate StatisticsGen with the ExampleGen ingested dataset
statistics_gen = tfx.components.StatisticsGen(
    examples=example_gen.outputs['examples'])

# Execute the component
context.run(statistics_gen)

ExecutionResult(
    component_id: StatisticsGen
    execution_id: 31
    outputs:
        statistics: OutputChannel(artifact_type=ExampleStatistics, producer_component_id=StatisticsGen, output_key=statistics, additional_properties={}, additional_custom_properties={}, _input_trigger=None)

You can display the statistics with the `show()` method.

*Note: You can safely ignore the warning shown when running the cell below.*

In [14]:
# Show the output statistics
context.show(statistics_gen.outputs['statistics'])

### SchemaGen

The [SchemaGen](https://www.tensorflow.org/tfx/guide/schemagen) component also uses TFDV to generate a schema based on your data statistics. As you've learned previously, a schema defines the expected bounds, types, and properties of the features in your dataset.

`SchemaGen` will take as input the statistics that we generated with `StatisticsGen`, looking at the training split by default.

In [15]:
# Instantiate SchemaGen with the StatisticsGen ingested dataset
schema_gen = tfx.components.SchemaGen(
    statistics=statistics_gen.outputs['statistics'],
    )

# Run the component
context.run(schema_gen)

ExecutionResult(
    component_id: SchemaGen
    execution_id: 32
    outputs:
        schema: OutputChannel(artifact_type=Schema, producer_component_id=SchemaGen, output_key=schema, additional_properties={}, additional_custom_properties={}, _input_trigger=None)

You can then visualize the generated schema as a table.

In [16]:
# Visualize the schema
context.show(schema_gen.outputs['schema'])

                               Type  Presence Valency             Domain
Feature name
'Date'                        BYTES  required                          -
'Dew_point_temperature__C_'   FLOAT  required                          -
'Functioning_Day'            STRING  required          'Functioning_Day'
'Holiday'                    STRING  required                  'Holiday'
'Hour'                          INT  required                          -
'Humidity___'                   INT  required                          -
'Rainfall_mm_'                FLOAT  required                          -
'Rented_Bike_Count'             INT  required                          -
'Seasons'                    STRING  required                  'Seasons'
'Snowfall__cm_'               FLOAT  required                          -
'Solar_Radiation__MJ_m2_'     FLOAT  required                          -
'Temperature__C_'             FLOAT  required                          -
'Visibility__10m_'              INT  required                          -
'Wind_speed__m_s_'            FLOAT  required                          -

                                                   Values
Domain
'Functioning_Day'                             'No', 'Yes'
'Holiday'                         'Holiday', 'No Holiday'
'Seasons'          'Autumn', 'Spring', 'Summer', 'Winter'

Let's now move to the next step in the pipeline and see if there are any anomalies in the data.

### ExampleValidator

The [ExampleValidator](https://www.tensorflow.org/tfx/guide/exampleval) component detects anomalies in your data based on the generated schema from the previous step. Like the previous two components, it also uses TFDV under the hood. 

`ExampleValidator` will take as input the statistics from `StatisticsGen` and the schema from `SchemaGen`. By default, it compares the statistics from the evaluation split to the schema from the training split.

In [17]:
# Instantiate ExampleValidator with the StatisticsGen and SchemaGen ingested data
example_validator = tfx.components.ExampleValidator(
    statistics=statistics_gen.outputs['statistics'],
    schema=schema_gen.outputs['schema'])

# Run the component.
context.run(example_validator)

ExecutionResult(
    component_id: ExampleValidator
    execution_id: 33
    outputs:
        anomalies: OutputChannel(artifact_type=ExampleAnomalies, producer_component_id=ExampleValidator, output_key=anomalies, additional_properties={}, additional_custom_properties={}, _input_trigger=None)

As with the previous component, you can also visualize the anomalies as a table.

In [18]:
# Visualize the results
context.show(example_validator.outputs['anomalies'])

With no anomalies detected, you can proceed to the next step in the pipeline.

### Transform
The [Transform](https://www.tensorflow.org/tfx/guide/transform) component performs feature engineering for both training and serving datasets. It uses the [TensorFlow Transform](https://www.tensorflow.org/tfx/transform/get_started) library introduced in the first ungraded lab of this week.

`Transform` will take as input the data from `ExampleGen`, the schema from `SchemaGen`, as well as a module containing the preprocessing function.

In this section, you will work on an example of a user-defined Transform code. The pipeline needs to load this as a module so you need to use the magic command `%% writefile` to save the file to disk. Let's first define a few constants that group the data's attributes according to the transforms we will perform later. This file will also be saved locally.

In [19]:
# Set the constants module filename
_bike_constants_module_file = 'bike_constants.py'

In [20]:
%%writefile {_bike_constants_module_file}

# Features with string data types that will be converted to indices
CATEGORICAL_FEATURE_KEYS = ['Seasons', 'Holiday', 'Functioning_Day']

# Numerical features that are marked as continuous
NUMERIC_FEATURE_KEYS = ['Temperature__C_', 'Humidity___', 'Wind_speed__m_s_', 'Visibility__10m_', 'Dew_point_temperature__C_', 'Solar_Radiation__MJ_m2_', 'Rainfall_mm_', 'Snowfall__cm_']

# Feature that can be grouped into buckets
BUCKET_FEATURE_KEYS = ['Hour']

# Number of buckets used by tf.transform for encoding each bucket feature.
FEATURE_BUCKET_COUNT = {'Hour': 4}

# Feature that the model will predict
LABEL_KEY = 'Rented_Bike_Count'

# Utility function for renaming the feature
def transformed_name(key):
    return key + '_xf'

Overwriting bike_constants.py

Next, you will work on the module that contains `preprocessing_fn()`. As you've seen in the previous lab, this function defines how you will transform the raw data into features that your model can train on (i.e. the next step in the pipeline). You will use the [tft module functions](https://www.tensorflow.org/tfx/transform/api_docs/python/tft) to make these transformations. 

*Note: After completing the entire notebook, we encourage you to go back to this section and try different tft functions aside from the ones already provided below. You can also modify the grouping of the feature keys in the constants file if you want. For example, you may want to scale some features to `[0, 1]` while others are scaled to the z-score. This will be good practice for this week's assignment.*

In [21]:
# Set the transform module filename
_bike_transform_module_file = 'bike_transform.py'

In [ ]:
%%writefile {_bike_transform_module_file}

import tensorflow as tf
import tensorflow_transform as tft

import bike_constants

# Unpack the contents of the constants module
_NUMERIC_FEATURE_KEYS = bike_constants.NUMERIC_FEATURE_KEYS
_CATEGORICAL_FEATURE_KEYS = bike_constants.CATEGORICAL_FEATURE_KEYS
_BUCKET_FEATURE_KEYS = bike_constants.BUCKET_FEATURE_KEYS
_FEATURE_BUCKET_COUNT = bike_constants.FEATURE_BUCKET_COUNT
_LABEL_KEY = bike_constants.LABEL_KEY
_transformed_name = bike_constants.transformed_name

# Define the transformations
def preprocessing_fn(inputs):
    outputs = {}

    month_str = tf.strings.substr(inputs['Date'], 3, 2)
    outputs['Month_xf'] = tft.compute_and_apply_vocabulary(month_str)

    # Temperature * Wind_speed
    wind_chill_raw = tf.multiply(inputs['Temperature__C_'], inputs['Wind_speed__m_s_'])
    outputs['Wind_Chill_xf'] = tft.scale_to_z_score(wind_chill_raw)

    # Scale these features using z-score
    for key in _NUMERIC_FEATURE_KEYS:
        outputs[_transformed_name(key)] = tft.scale_to_z_score(inputs[key])
    
    # Bucketize these features
    for key in _BUCKET_FEATURE_KEYS:
        outputs[_transformed_name(key)] = tft.bucketize(
            inputs[key], _FEATURE_BUCKET_COUNT[key])

    # Convert strings to indices in a vocabulary
    for key in _CATEGORICAL_FEATURE_KEYS:
        outputs[_transformed_name(key)] = tft.compute_and_apply_vocabulary(inputs[key])

    # Extract the string representation of Bucketized Hour
    hour_bucket_name = _transformed_name('Hour')
    hour_str = tf.strings.as_string(outputs[hour_bucket_name])

    # Cross exactly with Seasons input
    season_str = inputs['Seasons']
    crossed_feature = tf.strings.join([hour_str, season_str], separator='_')
    
    # Apply vocabulary to the crossed feature
    outputs['Hour_cross_Seasons_xf'] = tft.compute_and_apply_vocabulary(crossed_feature)

    # Cast label to float
    outputs[_transformed_name(_LABEL_KEY)] = tf.cast(inputs[_LABEL_KEY], tf.float32)

    return outputs

Overwriting bike_transform.py

You can now pass the training data, schema, and transform module to the `Transform` component. You can ignore the warning messages generated by Apache Beam regarding type hints.

In [23]:
# Ignore TF warning messages
tf.get_logger().setLevel('ERROR')

# Instantiate the Transform component
transform = tfx.components.Transform(
    examples=example_gen.outputs['examples'],
    schema=schema_gen.outputs['schema'],
    module_file=os.path.abspath(_bike_transform_module_file))

# Run the component
context.run(transform)

WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary/apply_vocab/text_file_init/InitializeTableFromTextFileV2
WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary_1/apply_vocab/text_file_init/InitializeTableFromTextFileV2
WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary_2/apply_vocab/text_file_init/InitializeTableFromTextFileV2
WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary_3/apply_vocab/text_file_init/InitializeTableFromTextFileV2
WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary_4/apply_vocab/text_file_init/InitializeTableFromTextFileV2
WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary/apply_vocab/text_file_init/InitializeTableFromTextFileV2
WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary_1/apply_vocab/text_file_init/InitializeTableFromTextFileV2
WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary_2/apply_vocab/text_file_init/InitializeTableFromTextFileV2
WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary_3/apply_vocab/text_file_init/InitializeTableFromTextFileV2
WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary_4/apply_vocab/text_file_init/InitializeTableFromTextFileV2
WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary/apply_vocab/text_file_init/InitializeTableFromTextFileV2
WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary_1/apply_vocab/text_file_init/InitializeTableFromTextFileV2
WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary_2/apply_vocab/text_file_init/InitializeTableFromTextFileV2
WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary_3/apply_vocab/text_file_init/InitializeTableFromTextFileV2
WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary_4/apply_vocab/text_file_init/InitializeTableFromTextFileV2
WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary/apply_vocab/text_file_init/InitializeTableFromTextFileV2
WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary_1/apply_vocab/text_file_init/InitializeTableFromTextFileV2
WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary_2/apply_vocab/text_file_init/InitializeTableFromTextFileV2
WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary_3/apply_vocab/text_file_init/InitializeTableFromTextFileV2
WARNING:absl:Tables initialized inside a tf.function  will be re-initialized on every invocation of the function. This  re-initialization can have significant impact on performance. Consider lifting  them out of the graph context using  `tf.init_scope`.: compute_and_apply_vocabulary_4/apply_vocab/text_file_init/InitializeTableFromTextFileV2
WARNING:absl:Analyzer (compute_and_apply_vocabulary_4/vocabulary/temporary_analyzer_output/vocab_compute_and_apply_vocabulary_4_vocabulary_unpruned_vocab_size:0) node's cache key varies on repeated tracing. This warning is safe to ignore if you either specify `name` for all analyzers or if the order in which they are invoked is deterministic. If not, please file a bug with details.
WARNING:absl:Analyzer (compute_and_apply_vocabulary_4/vocabulary/temporary_analyzer_output_1/vocab_compute_and_apply_vocabulary_4_vocabulary_pruned_vocab_size:0) node's cache key varies on repeated tracing. This warning is safe to ignore if you either specify `name` for all analyzers or if the order in which they are invoked is deterministic. If not, please file a bug with details.
WARNING:absl:Analyzer (compute_and_apply_vocabulary_4/vocabulary/temporary_analyzer_output_2/Const:0) node's cache key varies on repeated tracing. This warning is safe to ignore if you either specify `name` for all analyzers or if the order in which they are invoked is deterministic. If not, please file a bug with details.
WARNING:absl:Analyzer (compute_and_apply_vocabulary_4/vocabulary/temporary_analyzer_output/vocab_compute_and_apply_vocabulary_4_vocabulary_unpruned_vocab_size:0) node's cache key varies on repeated tracing. This warning is safe to ignore if you either specify `name` for all analyzers or if the order in which they are invoked is deterministic. If not, please file a bug with details.
WARNING:absl:Analyzer (compute_and_apply_vocabulary_4/vocabulary/temporary_analyzer_output_1/vocab_compute_and_apply_vocabulary_4_vocabulary_pruned_vocab_size:0) node's cache key varies on repeated tracing. This warning is safe to ignore if you either specify `name` for all analyzers or if the order in which they are invoked is deterministic. If not, please file a bug with details.
WARNING:absl:Analyzer (compute_and_apply_vocabulary_4/vocabulary/temporary_analyzer_output_2/Const:0) node's cache key varies on repeated tracing. This warning is safe to ignore if you either specify `name` for all analyzers or if the order in which they are invoked is deterministic. If not, please file a bug with details.

ExecutionResult(
    component_id: Transform
    execution_id: 34
    outputs:
        transform_graph: OutputChannel(artifact_type=TransformGraph, producer_component_id=Transform, output_key=transform_graph, additional_properties={}, additional_custom_properties={}, _input_trigger=None
        transformed_examples: OutputChannel(artifact_type=Examples, producer_component_id=Transform, output_key=transformed_examples, additional_properties={}, additional_custom_properties={}, _input_trigger=None
        updated_analyzer_cache: OutputChannel(artifact_type=TransformCache, producer_component_id=Transform, output_key=updated_analyzer_cache, additional_properties={}, additional_custom_properties={}, _input_trigger=None
        pre_transform_schema: OutputChannel(artifact_type=Schema, producer_component_id=Transform, output_key=pre_transform_schema, additional_properties={}, additional_custom_properties={}, _input_trigger=None
        pre_transform_stats: OutputChannel(artifact_type=ExampleStatistics, producer_component_id=Transform, output_key=pre_transform_stats, additional_properties={}, additional_custom_properties={}, _input_trigger=None
        post_transform_schema: OutputChannel(artifact_type=Schema, producer_component_id=Transform, output_key=post_transform_schema, additional_properties={}, additional_custom_properties={}, _input_trigger=None
        post_transform_stats: OutputChannel(artifact_type=ExampleStatistics, producer_component_id=Transform, output_key=post_transform_stats, additional_properties={}, additional_custom_properties={}, _input_trigger=None
        post_transform_anomalies: OutputChannel(artifact_type=ExampleAnomalies, producer_component_id=Transform, output_key=post_transform_anomalies, additional_properties={}, additional_custom_properties={}, _input_trigger=None)

Let's examine the output artifacts of `Transform` (i.e. `.component.outputs` from the output cell above). This component produces several outputs:

* `transform_graph` is the graph that can perform the preprocessing operations. This graph will be included during training and serving to ensure consistent transformations of incoming data.
* `transformed_examples` points to the preprocessed training and evaluation data.
* `updated_analyzer_cache` are stored calculations from previous runs.

Take a peek at the `transform_graph` artifact.  It points to a directory containing three subdirectories.

In [24]:
# Get the uri of the transform graph
transform_graph_uri = transform.outputs['transform_graph'].get()[0].uri

# List the subdirectories under the uri
os.listdir(transform_graph_uri)

['metadata', 'transformed_metadata', 'transform_fn']

* The `metadata` subdirectory contains the schema of the original data.
* The `transformed_metadata` subdirectory contains the schema of the preprocessed data. 
* The `transform_fn` subdirectory contains the actual preprocessing graph. 

You can also take a look at the first three transformed examples using the helper function defined earlier.

In [25]:
# Get the URI of the output artifact representing the transformed examples
train_uri = os.path.join(transform.outputs['transformed_examples'].get()[0].uri, 'Split-train')

# Get the list of files in this directory (all compressed TFRecord files)
tfrecord_filenames = [os.path.join(train_uri, name)
                      for name in os.listdir(train_uri)]

# Create a `TFRecordDataset` to read these files
transformed_dataset = tf.data.TFRecordDataset(tfrecord_filenames, compression_type="GZIP")

In [26]:
# Get 3 records from the dataset
sample_records_xf = get_records(transformed_dataset, 3)

# Print the output
pp.pprint(sample_records_xf)

[{'features': {'feature': {'Dew_point_temperature__C__xf': {'floatList': {'value': [-1.6579038]}},
                           'Functioning_Day_xf': {'int64List': {'value': ['0']}},
                           'Holiday_xf': {'int64List': {'value': ['0']}},
                           'Hour_cross_Seasons_xf': {'int64List': {'value': ['9']}},
                           'Hour_xf': {'int64List': {'value': ['0']}},
                           'Humidity____xf': {'floatList': {'value': [-1.0439466]}},
                           'Month_xf': {'int64List': {'value': ['7']}},
                           'Rainfall_mm__xf': {'floatList': {'value': [-0.13876215]}},
                           'Rented_Bike_Count_xf': {'floatList': {'value': [254.0]}},
                           'Seasons_xf': {'int64List': {'value': ['2']}},
                           'Snowfall__cm__xf': {'floatList': {'value': [-0.17444625]}},
                           'Solar_Radiation__MJ_m2__xf': {'floatList': {'value': [-0.6549028]}},
                           'Temperature__C__xf': {'floatList': {'value': [-1.5093157]}},
                           'Visibility__10m__xf': {'floatList': {'value': [0.9289351]}},
                           'Wind_Chill_xf': {'floatList': {'value': [-1.1829658]}},
                           'Wind_speed__m_s__xf': {'floatList': {'value': [0.44521824]}}}}},
 {'features': {'feature': {'Dew_point_temperature__C__xf': {'floatList': {'value': [-1.6579038]}},
                           'Functioning_Day_xf': {'int64List': {'value': ['0']}},
                           'Holiday_xf': {'int64List': {'value': ['0']}},
                           'Hour_cross_Seasons_xf': {'int64List': {'value': ['9']}},
                           'Hour_xf': {'int64List': {'value': ['0']}},
                           'Humidity____xf': {'floatList': {'value': [-0.99487084]}},
                           'Month_xf': {'int64List': {'value': ['7']}},
                           'Rainfall_mm__xf': {'floatList': {'value': [-0.13876215]}},
                           'Rented_Bike_Count_xf': {'floatList': {'value': [204.0]}},
                           'Seasons_xf': {'int64List': {'value': ['2']}},
                           'Snowfall__cm__xf': {'floatList': {'value': [-0.17444625]}},
                           'Solar_Radiation__MJ_m2__xf': {'floatList': {'value': [-0.6549028]}},
                           'Temperature__C__xf': {'floatList': {'value': [-1.5343859]}},
                           'Visibility__10m__xf': {'floatList': {'value': [0.9289351]}},
                           'Wind_Chill_xf': {'floatList': {'value': [-0.93321854]}},
                           'Wind_speed__m_s__xf': {'floatList': {'value': [-0.9014611]}}}}},
 {'features': {'feature': {'Dew_point_temperature__C__xf': {'floatList': {'value': [-1.6655546]}},
                           'Functioning_Day_xf': {'int64List': {'value': ['0']}},
                           'Holiday_xf': {'int64List': {'value': ['0']}},
                           'Hour_cross_Seasons_xf': {'int64List': {'value': ['9']}},
                           'Hour_xf': {'int64List': {'value': ['0']}},
                           'Humidity____xf': {'floatList': {'value': [-0.9457951]}},
                           'Month_xf': {'int64List': {'value': ['7']}},
                           'Rainfall_mm__xf': {'floatList': {'value': [-0.13876215]}},
                           'Rented_Bike_Count_xf': {'floatList': {'value': [173.0]}},
                           'Seasons_xf': {'int64List': {'value': ['2']}},
                           'Snowfall__cm__xf': {'floatList': {'value': [-0.17444625]}},
                           'Solar_Radiation__MJ_m2__xf': {'floatList': {'value': [-0.6549028]}},
                           'Temperature__C__xf': {'floatList': {'value': [-1.5761696]}},
                           'Visibility__10m__xf': {'floatList': {'value': [0.9289351]}},
                           'Wind_Chill_xf': {'floatList': {'value': [-0.98997927]}},
                           'Wind_speed__m_s__xf': {'floatList': {'value': [-0.7090784]}}}}}]

### Trainer Component

The `Trainer` component will ingest the transformed examples and the graph to robustly train a Keras Neural Network.

In [27]:
_bike_trainer_module_file = 'bike_trainer.py'

In [28]:
%%writefile {_bike_trainer_module_file}
import tensorflow as tf
import tensorflow_transform as tft
from tfx.components.trainer.fn_args_utils import FnArgs
import bike_constants

_LABEL_KEY = bike_constants.LABEL_KEY
_transformed_name = bike_constants.transformed_name

def _gzip_reader_fn(filenames):
    return tf.data.TFRecordDataset(filenames, compression_type='GZIP')

def _input_fn(file_pattern, tf_transform_output, batch_size=64):
    dataset = tf.data.experimental.make_batched_features_dataset(
        file_pattern=file_pattern,
        batch_size=batch_size,
        features=tf_transform_output.transformed_feature_spec(),
        reader=_gzip_reader_fn,
        label_key=_transformed_name(_LABEL_KEY))
    return dataset


def _build_keras_model(tf_transform_output, hidden_units=[64, 32]):
    feature_spec = tf_transform_output.transformed_feature_spec()
    feature_spec.pop(_transformed_name(_LABEL_KEY))
    
    inputs = {}
    for key, spec in feature_spec.items():
        inputs[key] = tf.keras.layers.Input(shape=spec.shape, name=key, dtype=spec.dtype)

    flattened_inputs = []
    for key, tensor in inputs.items():
        if tensor.dtype != tf.float32:
            flattened_inputs.append(tf.cast(tensor, tf.float32))
        else:
            flattened_inputs.append(tensor)
            
    concat = tf.keras.layers.Concatenate()(flattened_inputs)
    x = concat
    for layer_size in hidden_units:
        x = tf.keras.layers.Dense(layer_size, activation='relu')(x)
    
    output = tf.keras.layers.Dense(1)(x)
    model = tf.keras.Model(inputs=inputs, outputs=output)
    model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.01), loss='mse', metrics=['mae'])
    return model

def _get_serve_tf_examples_fn(model, tf_transform_output):
    model.tft_layer = tf_transform_output.transform_features_layer()
    @tf.function
    def serve_tf_examples_fn(serialized_tf_examples):
        feature_spec = tf_transform_output.raw_feature_spec()
        feature_spec.pop(_LABEL_KEY)
        parsed_features = tf.io.parse_example(serialized_tf_examples, feature_spec)
        transformed_features = model.tft_layer(parsed_features)
        return model(transformed_features)
    return serve_tf_examples_fn

def run_fn(fn_args: FnArgs):
    tf_transform_output = tft.TFTransformOutput(fn_args.transform_output)
    
    train_dataset = _input_fn(fn_args.train_files[0], tf_transform_output)
    eval_dataset = _input_fn(fn_args.eval_files[0], tf_transform_output)

    model = _build_keras_model(tf_transform_output)
    
    model.fit(
        train_dataset,
        steps_per_epoch=fn_args.train_steps,
        validation_data=eval_dataset,
        validation_steps=fn_args.eval_steps,
        epochs=1) # Just 1 epoch for PoC fast execution

    signatures = {
        'serving_default': _get_serve_tf_examples_fn(model, tf_transform_output).get_concrete_function(
            tf.TensorSpec(shape=[None], dtype=tf.string, name='examples'))
    }
    model.save(fn_args.serving_model_dir, save_format='tf', signatures=signatures)

Overwriting bike_trainer.py

In [29]:
trainer = tfx.components.Trainer(
    module_file=os.path.abspath(_bike_trainer_module_file),
    examples=transform.outputs['transformed_examples'],
    transform_graph=transform.outputs['transform_graph'],
    schema=schema_gen.outputs['schema'],
    train_args=tfx.proto.TrainArgs(num_steps=100),
    eval_args=tfx.proto.EvalArgs(num_steps=50))
    
context.run(trainer)

WARNING:absl:Examples artifact does not have payload_format custom property. Falling back to FORMAT_TF_EXAMPLE
WARNING:absl:Examples artifact does not have payload_format custom property. Falling back to FORMAT_TF_EXAMPLE
WARNING:absl:Examples artifact does not have payload_format custom property. Falling back to FORMAT_TF_EXAMPLE

100/100 [==============================] - 1s 3ms/step - loss: 426559.1250 - mae: 459.5307 - val_loss: 198833.6406 - val_mae: 322.2873

ExecutionResult(
    component_id: Trainer
    execution_id: 35
    outputs:
        model: OutputChannel(artifact_type=Model, producer_component_id=Trainer, output_key=model, additional_properties={}, additional_custom_properties={}, _input_trigger=None
        model_run: OutputChannel(artifact_type=ModelRun, producer_component_id=Trainer, output_key=model_run, additional_properties={}, additional_custom_properties={}, _input_trigger=None)

### Evaluator Component (TFMA)
Evaluates the model horizontally across slices (e.g. tracking Winter subset MSE against Summer MSE)

In [30]:
import tensorflow_model_analysis as tfma

eval_config = tfma.EvalConfig(
    model_specs=[tfma.ModelSpec(label_key='Rented_Bike_Count')],
    slicing_specs=[
        tfma.SlicingSpec(),
        tfma.SlicingSpec(feature_keys=['Seasons']) # Slicing by season explicitly!
    ],
    metrics_specs=[
        tfma.MetricsSpec(metrics=[
            tfma.MetricConfig(class_name='MeanSquaredError'),
            tfma.MetricConfig(class_name='MeanAbsoluteError')
        ])
    ]
)

evaluator = tfx.components.Evaluator(
    examples=example_gen.outputs['examples'],
    model=trainer.outputs['model'],
    eval_config=eval_config)

context.run(evaluator)

ExecutionResult(
    component_id: Evaluator
    execution_id: 36
    outputs:
        evaluation: OutputChannel(artifact_type=ModelEvaluation, producer_component_id=Evaluator, output_key=evaluation, additional_properties={}, additional_custom_properties={}, _input_trigger=None
        blessing: OutputChannel(artifact_type=ModelBlessing, producer_component_id=Evaluator, output_key=blessing, additional_properties={}, additional_custom_properties={}, _input_trigger=None)